### ISSUE TITLE
Alternative mirror for data and rules.hash files.

### ISSUE THREAD

**Issue by bb10** [ClearURLs/Rules#5] opened 2020-08-25 04:05 UTC
Could you please provide an (non-google cloud hosted) alternative mirror for https://kevinroebert.gitlab.io/?

Specifically for https://kevinroebert.gitlab.io/ClearUrls/data/data.minify.json and https://kevinroebert.gitlab.io/ClearUrls/data/rules.minify.hash. And also the test page if possible.

A github.io mirror would be fine.

Thank you.

**Comment by KevinRoebert** [comment] 2020-09-01 20:40
> 
> 
> Could you please provide an (non-google cloud hosted) alternative mirror for https://kevinroebert.gitlab.io/?
> 
> Specifically for https://kevinroebert.gitlab.io/ClearUrls/data/data.minify.json and https://kevinroebert.gitlab.io/ClearUrls/data/rules.minify.hash. And also the test page if possible.
> 
> A github.io mirror would be fine.
> 
> Thank you.

I've created a GitHub Action that also builds, tests and deploys on GitHub. The GitHub Pages mirror is reachable under this locations:

- https://rules2.clearurls.xyz/data.minify.json 
- https://rules2.clearurls.xyz/rules.minify.hash

**Comment by KevinRoebert** [comment] 2020-09-01 20:52
> @bb10  What I do personally is that update checking is done with a change detection and notification service, once a day, which informs me when available. 

This is exactly what is currently done in the background using the rules.minify.hash file. It contains the SHA-256 hash of the rules file. If this hash is different from the locally stored hash, the rules are downloaded. Of course, the hash also serves as an integrity check.

The Rules-Status field in the UI also indicates whether new rules were successfully downloaded.

The update check you suggest would, of course, have to check the GitLab or GitHub servers for updates in some way.

> I then download the updates manually into a local folder (localhost, not sure a local drive url would make it) which I indicate to ClearURLs settings in the The url to the data.json file (rules) and The url to the rules.hash file (hash) 

Unfortunately, it is not possible to specify a local file path. This is not allowed by browsers for security reasons. Otherwise, an addon could search the whole filesystem without the user noticing.

However, for version 2.0, a ticket/feature is already open in GitLab to allow users to manually upload rule files to the add-on storage using the browser's upload function.

Please read also these issues on GitLab because your Issue is a duplicate of these: https://gitlab.com/KevinRoebert/ClearUrls/-/issues/410 and also this issue: https://gitlab.com/KevinRoebert/ClearUrls/-/issues/465

**Closed by KevinRoebert** 2020-09-01 20:52 UTC
Labels: enhancement

**Comment by KevinRoebert** [comment] 2020-09-01 22:15
> And also the test page if possible.

The test page is now hosted on GitHub and available under this URL: https://test.clearurls.xyz/
Please don't forget to update the rules, so the site can work properly.
